version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: telegram_bot
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: telegram_bot
      DB_USER: my_user
      DB_PASSWORD: my_password
      BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - app-network


volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
