spring:
  application:
    name: tg-cooloftheday
  datasource:
    url: jdbc:mysql://localhost:3307/telegram_bot
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true